python extract_variants_in_all_samples.py HC01_common_list.txt HC01_common_ids.txt HC01_subs_in_all.txt 23 &> HC01_ext_var.log && mv HC01_ext_var.log HC01_ext_var.success
python extract_variants_in_all_samples.py HC02_common_list.txt HC02_common_ids.txt HC02_subs_in_all.txt 21 &> HC02_ext_var.log && mv HC02_ext_var.log HC02_ext_var.success
python extract_variants_in_all_samples.py HC03_common_list.txt HC03_common_ids.txt HC03_subs_in_all.txt 24 &> HC03_ext_var.log && mv HC03_ext_var.log HC03_ext_var.success
python extract_variants_in_all_samples.py HC04_common_list.txt HC04_common_ids.txt HC04_subs_in_all.txt 23 &> HC04_ext_var.log && mv HC04_ext_var.log HC04_ext_var.success
python extract_variants_in_all_samples.py HC05_common_list.txt HC05_common_ids.txt HC05_subs_in_all.txt 24 &> HC05_ext_var.log && mv HC05_ext_var.log HC05_ext_var.success
python extract_variants_in_all_samples.py HC06_common_list.txt HC06_common_ids.txt HC06_subs_in_all.txt 22 &> HC06_ext_var.log && mv HC06_ext_var.log HC06_ext_var.success
python extract_variants_in_all_samples.py HC08_common_list.txt HC08_common_ids.txt HC08_subs_in_all.txt 23 &> HC08_ext_var.log && mv HC08_ext_var.log HC08_ext_var.success
python extract_variants_in_all_samples.py HC09_common_list.txt HC09_common_ids.txt HC09_subs_in_all.txt 21 &> HC09_ext_var.log && mv HC09_ext_var.log HC09_ext_var.success
python extract_variants_in_all_samples.py HC10_common_list.txt HC10_common_ids.txt HC10_subs_in_all.txt 20 &> HC10_ext_var.log && mv HC10_ext_var.log HC10_ext_var.success
python extract_variants_in_all_samples.py HC12_common_list.txt HC12_common_ids.txt HC12_subs_in_all.txt 22 &> HC12_ext_var.log && mv HC12_ext_var.log HC12_ext_var.success
python extract_variants_in_all_samples.py HC13_common_list.txt HC13_common_ids.txt HC13_subs_in_all.txt 22 &> HC13_ext_var.log && mv HC13_ext_var.log HC13_ext_var.success
python extract_variants_in_all_samples.py HC14_common_list.txt HC14_common_ids.txt HC14_subs_in_all.txt 19 &> HC14_ext_var.log && mv HC14_ext_var.log HC14_ext_var.success
python extract_variants_in_all_samples.py HC16_common_list.txt HC16_common_ids.txt HC16_subs_in_all.txt 18 &> HC16_ext_var.log && mv HC16_ext_var.log HC16_ext_var.success
python extract_variants_in_all_samples.py HC17_common_list.txt HC17_common_ids.txt HC17_subs_in_all.txt 14 &> HC17_ext_var.log && mv HC17_ext_var.log HC17_ext_var.success
python extract_variants_in_all_samples.py HC18_common_list.txt HC18_common_ids.txt HC18_subs_in_all.txt 17 &> HC18_ext_var.log && mv HC18_ext_var.log HC18_ext_var.success
python extract_variants_in_all_samples.py HC19_common_list.txt HC19_common_ids.txt HC19_subs_in_all.txt 23 &> HC19_ext_var.log && mv HC19_ext_var.log HC19_ext_var.success
python extract_variants_in_all_samples.py HC20_common_list.txt HC20_common_ids.txt HC20_subs_in_all.txt 22 &> HC20_ext_var.log && mv HC20_ext_var.log HC20_ext_var.success
python extract_variants_in_all_samples.py HC21_common_list.txt HC21_common_ids.txt HC21_subs_in_all.txt 23 &> HC21_ext_var.log && mv HC21_ext_var.log HC21_ext_var.success
