python remove_common_variants.py HC01_common_list.txt HC01_subs_in_all.txt &> HC01_rm_cmn.log && mv HC01_rm_cmn.log HC01_rm_cmn.success
python remove_common_variants.py HC02_common_list.txt HC02_subs_in_all.txt &> HC02_rm_cmn.log && mv HC02_rm_cmn.log HC02_rm_cmn.success
python remove_common_variants.py HC03_common_list.txt HC03_subs_in_all.txt &> HC03_rm_cmn.log && mv HC03_rm_cmn.log HC03_rm_cmn.success
python remove_common_variants.py HC04_common_list.txt HC04_subs_in_all.txt &> HC04_rm_cmn.log && mv HC04_rm_cmn.log HC04_rm_cmn.success
python remove_common_variants.py HC05_common_list.txt HC05_subs_in_all.txt &> HC05_rm_cmn.log && mv HC05_rm_cmn.log HC05_rm_cmn.success
python remove_common_variants.py HC06_common_list.txt HC06_subs_in_all.txt &> HC06_rm_cmn.log && mv HC06_rm_cmn.log HC06_rm_cmn.success
python remove_common_variants.py HC08_common_list.txt HC08_subs_in_all.txt &> HC08_rm_cmn.log && mv HC08_rm_cmn.log HC08_rm_cmn.success
python remove_common_variants.py HC09_common_list.txt HC09_subs_in_all.txt &> HC09_rm_cmn.log && mv HC09_rm_cmn.log HC09_rm_cmn.success
python remove_common_variants.py HC10_common_list.txt HC10_subs_in_all.txt &> HC10_rm_cmn.log && mv HC10_rm_cmn.log HC10_rm_cmn.success
python remove_common_variants.py HC12_common_list.txt HC12_subs_in_all.txt &> HC12_rm_cmn.log && mv HC12_rm_cmn.log HC12_rm_cmn.success
python remove_common_variants.py HC13_common_list.txt HC13_subs_in_all.txt &> HC13_rm_cmn.log && mv HC13_rm_cmn.log HC13_rm_cmn.success
python remove_common_variants.py HC14_common_list.txt HC14_subs_in_all.txt &> HC14_rm_cmn.log && mv HC14_rm_cmn.log HC14_rm_cmn.success
python remove_common_variants.py HC16_common_list.txt HC16_subs_in_all.txt &> HC16_rm_cmn.log && mv HC16_rm_cmn.log HC16_rm_cmn.success
python remove_common_variants.py HC17_common_list.txt HC17_subs_in_all.txt &> HC17_rm_cmn.log && mv HC17_rm_cmn.log HC17_rm_cmn.success
python remove_common_variants.py HC18_common_list.txt HC18_subs_in_all.txt &> HC18_rm_cmn.log && mv HC18_rm_cmn.log HC18_rm_cmn.success
python remove_common_variants.py HC19_common_list.txt HC19_subs_in_all.txt &> HC19_rm_cmn.log && mv HC19_rm_cmn.log HC19_rm_cmn.success
python remove_common_variants.py HC20_common_list.txt HC20_subs_in_all.txt &> HC20_rm_cmn.log && mv HC20_rm_cmn.log HC20_rm_cmn.success
python remove_common_variants.py HC21_common_list.txt HC21_subs_in_all.txt &> HC21_rm_cmn.log && mv HC21_rm_cmn.log HC21_rm_cmn.success
