sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC06-21.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC06-21.np_annot.log && mv HC06-21.np_annot.log HC06-21.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC12-10.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC12-10.np_annot.log && mv HC12-10.np_annot.log HC12-10.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC21-12.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC21-12.np_annot.log && mv HC21-12.np_annot.log HC21-12.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC05-10.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC05-10.np_annot.log && mv HC05-10.np_annot.log HC05-10.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC20-07.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC20-07.np_annot.log && mv HC20-07.np_annot.log HC20-07.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC09-20.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC09-20.np_annot.log && mv HC09-20.np_annot.log HC09-20.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC16-03.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC16-03.np_annot.log && mv HC16-03.np_annot.log HC16-03.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC13-06.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC13-06.np_annot.log && mv HC13-06.np_annot.log HC13-06.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC13-21.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC13-21.np_annot.log && mv HC13-21.np_annot.log HC13-21.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC08-14.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC08-14.np_annot.log && mv HC08-14.np_annot.log HC08-14.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC18-09.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC18-09.np_annot.log && mv HC18-09.np_annot.log HC18-09.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC14-08.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC14-08.np_annot.log && mv HC14-08.np_annot.log HC14-08.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC12-17.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC12-17.np_annot.log && mv HC12-17.np_annot.log HC12-17.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC04-03.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC04-03.np_annot.log && mv HC04-03.np_annot.log HC04-03.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC05-24.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC05-24.np_annot.log && mv HC05-24.np_annot.log HC05-24.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC01-20.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC01-20.np_annot.log && mv HC01-20.np_annot.log HC01-20.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC18-16.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC18-16.np_annot.log && mv HC18-16.np_annot.log HC18-16.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC21-17.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC21-17.np_annot.log && mv HC21-17.np_annot.log HC21-17.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC15-18.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC15-18.np_annot.log && mv HC15-18.np_annot.log HC15-18.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC08-11.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC08-11.np_annot.log && mv HC08-11.np_annot.log HC08-11.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC18-13.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC18-13.np_annot.log && mv HC18-13.np_annot.log HC18-13.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC13-13.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC13-13.np_annot.log && mv HC13-13.np_annot.log HC13-13.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC15-09.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC15-09.np_annot.log && mv HC15-09.np_annot.log HC15-09.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC14-12.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC14-12.np_annot.log && mv HC14-12.np_annot.log HC14-12.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC16-15.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC16-15.np_annot.log && mv HC16-15.np_annot.log HC16-15.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC06-05.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC06-05.np_annot.log && mv HC06-05.np_annot.log HC06-05.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC19-17.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC19-17.np_annot.log && mv HC19-17.np_annot.log HC19-17.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC09-17.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC09-17.np_annot.log && mv HC09-17.np_annot.log HC09-17.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC15-01.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC15-01.np_annot.log && mv HC15-01.np_annot.log HC15-01.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC06-11.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC06-11.np_annot.log && mv HC06-11.np_annot.log HC06-11.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC19-20.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC19-20.np_annot.log && mv HC19-20.np_annot.log HC19-20.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC10-19.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC10-19.np_annot.log && mv HC10-19.np_annot.log HC10-19.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC03-18.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC03-18.np_annot.log && mv HC03-18.np_annot.log HC03-18.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC17-04.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC17-04.np_annot.log && mv HC17-04.np_annot.log HC17-04.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC08-13.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC08-13.np_annot.log && mv HC08-13.np_annot.log HC08-13.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC03-22.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC03-22.np_annot.log && mv HC03-22.np_annot.log HC03-22.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC04-18.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC04-18.np_annot.log && mv HC04-18.np_annot.log HC04-18.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC10-13.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC10-13.np_annot.log && mv HC10-13.np_annot.log HC10-13.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC19-08.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC19-08.np_annot.log && mv HC19-08.np_annot.log HC19-08.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC19-12.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC19-12.np_annot.log && mv HC19-12.np_annot.log HC19-12.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC20-17.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC20-17.np_annot.log && mv HC20-17.np_annot.log HC20-17.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC19-07.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC19-07.np_annot.log && mv HC19-07.np_annot.log HC19-07.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC03-02.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC03-02.np_annot.log && mv HC03-02.np_annot.log HC03-02.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC03-19.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC03-19.np_annot.log && mv HC03-19.np_annot.log HC03-19.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC19-22.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC19-22.np_annot.log && mv HC19-22.np_annot.log HC19-22.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC13-20.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC13-20.np_annot.log && mv HC13-20.np_annot.log HC13-20.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC21-05.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC21-05.np_annot.log && mv HC21-05.np_annot.log HC21-05.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC08-03.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC08-03.np_annot.log && mv HC08-03.np_annot.log HC08-03.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC13-15.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC13-15.np_annot.log && mv HC13-15.np_annot.log HC13-15.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC17-03.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC17-03.np_annot.log && mv HC17-03.np_annot.log HC17-03.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC06-02.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC06-02.np_annot.log && mv HC06-02.np_annot.log HC06-02.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC08-07.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC08-07.np_annot.log && mv HC08-07.np_annot.log HC08-07.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC06-12.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC06-12.np_annot.log && mv HC06-12.np_annot.log HC06-12.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC08-02.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC08-02.np_annot.log && mv HC08-02.np_annot.log HC08-02.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC05-20.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC05-20.np_annot.log && mv HC05-20.np_annot.log HC05-20.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC14-04.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC14-04.np_annot.log && mv HC14-04.np_annot.log HC14-04.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC01-03.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC01-03.np_annot.log && mv HC01-03.np_annot.log HC01-03.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC20-02.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC20-02.np_annot.log && mv HC20-02.np_annot.log HC20-02.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC12-08.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC12-08.np_annot.log && mv HC12-08.np_annot.log HC12-08.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC04-22.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC04-22.np_annot.log && mv HC04-22.np_annot.log HC04-22.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC08-20.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC08-20.np_annot.log && mv HC08-20.np_annot.log HC08-20.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC03-03.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC03-03.np_annot.log && mv HC03-03.np_annot.log HC03-03.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC16-06.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC16-06.np_annot.log && mv HC16-06.np_annot.log HC16-06.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC04-14.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC04-14.np_annot.log && mv HC04-14.np_annot.log HC04-14.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC17-12.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC17-12.np_annot.log && mv HC17-12.np_annot.log HC17-12.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC21-18.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC21-18.np_annot.log && mv HC21-18.np_annot.log HC21-18.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC13-09.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC13-09.np_annot.log && mv HC13-09.np_annot.log HC13-09.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC01-23.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC01-23.np_annot.log && mv HC01-23.np_annot.log HC01-23.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC18-10.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC18-10.np_annot.log && mv HC18-10.np_annot.log HC18-10.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC20-05.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC20-05.np_annot.log && mv HC20-05.np_annot.log HC20-05.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC06-07.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC06-07.np_annot.log && mv HC06-07.np_annot.log HC06-07.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC10-14.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC10-14.np_annot.log && mv HC10-14.np_annot.log HC10-14.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC03-10.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC03-10.np_annot.log && mv HC03-10.np_annot.log HC03-10.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC13-01.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC13-01.np_annot.log && mv HC13-01.np_annot.log HC13-01.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC01-21.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC01-21.np_annot.log && mv HC01-21.np_annot.log HC01-21.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC10-02.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC10-02.np_annot.log && mv HC10-02.np_annot.log HC10-02.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC04-01.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC04-01.np_annot.log && mv HC04-01.np_annot.log HC04-01.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC18-14.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC18-14.np_annot.log && mv HC18-14.np_annot.log HC18-14.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC21-07.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC21-07.np_annot.log && mv HC21-07.np_annot.log HC21-07.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC16-13.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC16-13.np_annot.log && mv HC16-13.np_annot.log HC16-13.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC09-02.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC09-02.np_annot.log && mv HC09-02.np_annot.log HC09-02.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC14-16.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC14-16.np_annot.log && mv HC14-16.np_annot.log HC14-16.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC20-04.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC20-04.np_annot.log && mv HC20-04.np_annot.log HC20-04.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC04-05.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC04-05.np_annot.log && mv HC04-05.np_annot.log HC04-05.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC08-15.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC08-15.np_annot.log && mv HC08-15.np_annot.log HC08-15.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC10-09.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC10-09.np_annot.log && mv HC10-09.np_annot.log HC10-09.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC05-01.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC05-01.np_annot.log && mv HC05-01.np_annot.log HC05-01.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC06-19.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC06-19.np_annot.log && mv HC06-19.np_annot.log HC06-19.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC01-12.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC01-12.np_annot.log && mv HC01-12.np_annot.log HC01-12.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC01-05.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC01-05.np_annot.log && mv HC01-05.np_annot.log HC01-05.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC04-07.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC04-07.np_annot.log && mv HC04-07.np_annot.log HC04-07.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC16-02.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC16-02.np_annot.log && mv HC16-02.np_annot.log HC16-02.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC08-05.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC08-05.np_annot.log && mv HC08-05.np_annot.log HC08-05.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC19-04.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC19-04.np_annot.log && mv HC19-04.np_annot.log HC19-04.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC12-11.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC12-11.np_annot.log && mv HC12-11.np_annot.log HC12-11.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC21-14.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC21-14.np_annot.log && mv HC21-14.np_annot.log HC21-14.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC03-20.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC03-20.np_annot.log && mv HC03-20.np_annot.log HC03-20.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC19-14.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC19-14.np_annot.log && mv HC19-14.np_annot.log HC19-14.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC04-15.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC04-15.np_annot.log && mv HC04-15.np_annot.log HC04-15.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC06-20.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC06-20.np_annot.log && mv HC06-20.np_annot.log HC06-20.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC15-16.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC15-16.np_annot.log && mv HC15-16.np_annot.log HC15-16.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC10-20.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC10-20.np_annot.log && mv HC10-20.np_annot.log HC10-20.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC06-22.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC06-22.np_annot.log && mv HC06-22.np_annot.log HC06-22.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC08-09.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC08-09.np_annot.log && mv HC08-09.np_annot.log HC08-09.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC12-09.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC12-09.np_annot.log && mv HC12-09.np_annot.log HC12-09.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC18-18.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC18-18.np_annot.log && mv HC18-18.np_annot.log HC18-18.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC16-12.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC16-12.np_annot.log && mv HC16-12.np_annot.log HC16-12.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC15-11.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC15-11.np_annot.log && mv HC15-11.np_annot.log HC15-11.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC01-04.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC01-04.np_annot.log && mv HC01-04.np_annot.log HC01-04.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC08-06.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC08-06.np_annot.log && mv HC08-06.np_annot.log HC08-06.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC03-21.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC03-21.np_annot.log && mv HC03-21.np_annot.log HC03-21.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC09-18.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC09-18.np_annot.log && mv HC09-18.np_annot.log HC09-18.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC18-17.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC18-17.np_annot.log && mv HC18-17.np_annot.log HC18-17.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC18-11.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC18-11.np_annot.log && mv HC18-11.np_annot.log HC18-11.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC09-16.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC09-16.np_annot.log && mv HC09-16.np_annot.log HC09-16.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC10-11.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC10-11.np_annot.log && mv HC10-11.np_annot.log HC10-11.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC12-22.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC12-22.np_annot.log && mv HC12-22.np_annot.log HC12-22.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC03-08.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC03-08.np_annot.log && mv HC03-08.np_annot.log HC03-08.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC15-04.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC15-04.np_annot.log && mv HC15-04.np_annot.log HC15-04.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC19-21.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC19-21.np_annot.log && mv HC19-21.np_annot.log HC19-21.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC03-07.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC03-07.np_annot.log && mv HC03-07.np_annot.log HC03-07.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC14-06.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC14-06.np_annot.log && mv HC14-06.np_annot.log HC14-06.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC14-01.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC14-01.np_annot.log && mv HC14-01.np_annot.log HC14-01.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC05-04.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC05-04.np_annot.log && mv HC05-04.np_annot.log HC05-04.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC05-17.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC05-17.np_annot.log && mv HC05-17.np_annot.log HC05-17.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC10-03.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC10-03.np_annot.log && mv HC10-03.np_annot.log HC10-03.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC16-08.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC16-08.np_annot.log && mv HC16-08.np_annot.log HC16-08.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC21-10.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC21-10.np_annot.log && mv HC21-10.np_annot.log HC21-10.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC15-12.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC15-12.np_annot.log && mv HC15-12.np_annot.log HC15-12.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC17-18.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC17-18.np_annot.log && mv HC17-18.np_annot.log HC17-18.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC06-18.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC06-18.np_annot.log && mv HC06-18.np_annot.log HC06-18.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC05-14.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC05-14.np_annot.log && mv HC05-14.np_annot.log HC05-14.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC19-03.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC19-03.np_annot.log && mv HC19-03.np_annot.log HC19-03.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC06-09.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC06-09.np_annot.log && mv HC06-09.np_annot.log HC06-09.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC10-10.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC10-10.np_annot.log && mv HC10-10.np_annot.log HC10-10.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC06-08.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC06-08.np_annot.log && mv HC06-08.np_annot.log HC06-08.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC15-03.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC15-03.np_annot.log && mv HC15-03.np_annot.log HC15-03.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC15-02.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC15-02.np_annot.log && mv HC15-02.np_annot.log HC15-02.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC14-15.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC14-15.np_annot.log && mv HC14-15.np_annot.log HC14-15.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC16-16.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC16-16.np_annot.log && mv HC16-16.np_annot.log HC16-16.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC16-05.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC16-05.np_annot.log && mv HC16-05.np_annot.log HC16-05.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC12-16.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC12-16.np_annot.log && mv HC12-16.np_annot.log HC12-16.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC21-23.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC21-23.np_annot.log && mv HC21-23.np_annot.log HC21-23.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC13-22.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC13-22.np_annot.log && mv HC13-22.np_annot.log HC13-22.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC19-10.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC19-10.np_annot.log && mv HC19-10.np_annot.log HC19-10.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC19-15.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC19-15.np_annot.log && mv HC19-15.np_annot.log HC19-15.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC09-01.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC09-01.np_annot.log && mv HC09-01.np_annot.log HC09-01.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC04-12.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC04-12.np_annot.log && mv HC04-12.np_annot.log HC04-12.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC18-03.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC18-03.np_annot.log && mv HC18-03.np_annot.log HC18-03.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC08-22.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC08-22.np_annot.log && mv HC08-22.np_annot.log HC08-22.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC17-17.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC17-17.np_annot.log && mv HC17-17.np_annot.log HC17-17.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC19-18.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC19-18.np_annot.log && mv HC19-18.np_annot.log HC19-18.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC09-14.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC09-14.np_annot.log && mv HC09-14.np_annot.log HC09-14.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC10-04.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC10-04.np_annot.log && mv HC10-04.np_annot.log HC10-04.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC08-21.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC08-21.np_annot.log && mv HC08-21.np_annot.log HC08-21.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC05-23.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC05-23.np_annot.log && mv HC05-23.np_annot.log HC05-23.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC13-18.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC13-18.np_annot.log && mv HC13-18.np_annot.log HC13-18.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC13-16.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC13-16.np_annot.log && mv HC13-16.np_annot.log HC13-16.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC17-01.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC17-01.np_annot.log && mv HC17-01.np_annot.log HC17-01.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC19-06.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC19-06.np_annot.log && mv HC19-06.np_annot.log HC19-06.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC21-06.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC21-06.np_annot.log && mv HC21-06.np_annot.log HC21-06.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC09-21.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC09-21.np_annot.log && mv HC09-21.np_annot.log HC09-21.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC15-06.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC15-06.np_annot.log && mv HC15-06.np_annot.log HC15-06.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC19-09.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC19-09.np_annot.log && mv HC19-09.np_annot.log HC19-09.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC08-10.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC08-10.np_annot.log && mv HC08-10.np_annot.log HC08-10.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC01-22.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC01-22.np_annot.log && mv HC01-22.np_annot.log HC01-22.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC03-06.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC03-06.np_annot.log && mv HC03-06.np_annot.log HC03-06.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC13-04.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC13-04.np_annot.log && mv HC13-04.np_annot.log HC13-04.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC19-02.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC19-02.np_annot.log && mv HC19-02.np_annot.log HC19-02.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC20-19.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC20-19.np_annot.log && mv HC20-19.np_annot.log HC20-19.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC05-12.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC05-12.np_annot.log && mv HC05-12.np_annot.log HC05-12.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC10-01.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC10-01.np_annot.log && mv HC10-01.np_annot.log HC10-01.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC08-19.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC08-19.np_annot.log && mv HC08-19.np_annot.log HC08-19.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC19-23.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC19-23.np_annot.log && mv HC19-23.np_annot.log HC19-23.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC04-11.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC04-11.np_annot.log && mv HC04-11.np_annot.log HC04-11.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC06-06.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC06-06.np_annot.log && mv HC06-06.np_annot.log HC06-06.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC15-23.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC15-23.np_annot.log && mv HC15-23.np_annot.log HC15-23.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC13-02.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC13-02.np_annot.log && mv HC13-02.np_annot.log HC13-02.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC13-17.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC13-17.np_annot.log && mv HC13-17.np_annot.log HC13-17.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC21-13.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC21-13.np_annot.log && mv HC21-13.np_annot.log HC21-13.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC01-15.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC01-15.np_annot.log && mv HC01-15.np_annot.log HC01-15.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC09-10.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC09-10.np_annot.log && mv HC09-10.np_annot.log HC09-10.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC17-16.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC17-16.np_annot.log && mv HC17-16.np_annot.log HC17-16.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC04-09.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC04-09.np_annot.log && mv HC04-09.np_annot.log HC04-09.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC21-19.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC21-19.np_annot.log && mv HC21-19.np_annot.log HC21-19.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC09-13.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC09-13.np_annot.log && mv HC09-13.np_annot.log HC09-13.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC06-13.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC06-13.np_annot.log && mv HC06-13.np_annot.log HC06-13.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC20-10.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC20-10.np_annot.log && mv HC20-10.np_annot.log HC20-10.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC14-14.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC14-14.np_annot.log && mv HC14-14.np_annot.log HC14-14.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC03-01.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC03-01.np_annot.log && mv HC03-01.np_annot.log HC03-01.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC21-15.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC21-15.np_annot.log && mv HC21-15.np_annot.log HC21-15.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC16-04.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC16-04.np_annot.log && mv HC16-04.np_annot.log HC16-04.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC05-03.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC05-03.np_annot.log && mv HC05-03.np_annot.log HC05-03.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC15-19.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC15-19.np_annot.log && mv HC15-19.np_annot.log HC15-19.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC13-10.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC13-10.np_annot.log && mv HC13-10.np_annot.log HC13-10.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC16-07.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC16-07.np_annot.log && mv HC16-07.np_annot.log HC16-07.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC14-02.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC14-02.np_annot.log && mv HC14-02.np_annot.log HC14-02.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC12-03.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC12-03.np_annot.log && mv HC12-03.np_annot.log HC12-03.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC13-12.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC13-12.np_annot.log && mv HC13-12.np_annot.log HC13-12.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC13-08.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC13-08.np_annot.log && mv HC13-08.np_annot.log HC13-08.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC09-15.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC09-15.np_annot.log && mv HC09-15.np_annot.log HC09-15.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC12-12.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC12-12.np_annot.log && mv HC12-12.np_annot.log HC12-12.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC20-03.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC20-03.np_annot.log && mv HC20-03.np_annot.log HC20-03.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC20-21.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC20-21.np_annot.log && mv HC20-21.np_annot.log HC20-21.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC20-06.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC20-06.np_annot.log && mv HC20-06.np_annot.log HC20-06.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC19-13.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC19-13.np_annot.log && mv HC19-13.np_annot.log HC19-13.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC16-14.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC16-14.np_annot.log && mv HC16-14.np_annot.log HC16-14.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC01-01.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC01-01.np_annot.log && mv HC01-01.np_annot.log HC01-01.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC21-22.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC21-22.np_annot.log && mv HC21-22.np_annot.log HC21-22.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC21-03.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC21-03.np_annot.log && mv HC21-03.np_annot.log HC21-03.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC16-11.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC16-11.np_annot.log && mv HC16-11.np_annot.log HC16-11.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC04-04.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC04-04.np_annot.log && mv HC04-04.np_annot.log HC04-04.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC12-06.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC12-06.np_annot.log && mv HC12-06.np_annot.log HC12-06.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC08-04.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC08-04.np_annot.log && mv HC08-04.np_annot.log HC08-04.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC21-04.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC21-04.np_annot.log && mv HC21-04.np_annot.log HC21-04.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC16-09.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC16-09.np_annot.log && mv HC16-09.np_annot.log HC16-09.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC06-03.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC06-03.np_annot.log && mv HC06-03.np_annot.log HC06-03.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC05-13.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC05-13.np_annot.log && mv HC05-13.np_annot.log HC05-13.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC20-09.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC20-09.np_annot.log && mv HC20-09.np_annot.log HC20-09.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC13-14.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC13-14.np_annot.log && mv HC13-14.np_annot.log HC13-14.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC04-10.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC04-10.np_annot.log && mv HC04-10.np_annot.log HC04-10.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC14-17.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC14-17.np_annot.log && mv HC14-17.np_annot.log HC14-17.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC19-19.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC19-19.np_annot.log && mv HC19-19.np_annot.log HC19-19.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC04-08.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC04-08.np_annot.log && mv HC04-08.np_annot.log HC04-08.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC16-19.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC16-19.np_annot.log && mv HC16-19.np_annot.log HC16-19.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC08-23.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC08-23.np_annot.log && mv HC08-23.np_annot.log HC08-23.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC19-01.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC19-01.np_annot.log && mv HC19-01.np_annot.log HC19-01.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC15-05.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC15-05.np_annot.log && mv HC15-05.np_annot.log HC15-05.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC12-04.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC12-04.np_annot.log && mv HC12-04.np_annot.log HC12-04.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC14-05.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC14-05.np_annot.log && mv HC14-05.np_annot.log HC14-05.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC01-10.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC01-10.np_annot.log && mv HC01-10.np_annot.log HC01-10.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC20-13.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC20-13.np_annot.log && mv HC20-13.np_annot.log HC20-13.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC06-16.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC06-16.np_annot.log && mv HC06-16.np_annot.log HC06-16.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC21-08.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC21-08.np_annot.log && mv HC21-08.np_annot.log HC21-08.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC08-12.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC08-12.np_annot.log && mv HC08-12.np_annot.log HC08-12.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC04-13.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC04-13.np_annot.log && mv HC04-13.np_annot.log HC04-13.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC20-01.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC20-01.np_annot.log && mv HC20-01.np_annot.log HC20-01.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC06-17.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC06-17.np_annot.log && mv HC06-17.np_annot.log HC06-17.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC01-17.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC01-17.np_annot.log && mv HC01-17.np_annot.log HC01-17.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC14-10.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC14-10.np_annot.log && mv HC14-10.np_annot.log HC14-10.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC03-16.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC03-16.np_annot.log && mv HC03-16.np_annot.log HC03-16.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC04-20.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC04-20.np_annot.log && mv HC04-20.np_annot.log HC04-20.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC20-12.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC20-12.np_annot.log && mv HC20-12.np_annot.log HC20-12.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC16-17.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC16-17.np_annot.log && mv HC16-17.np_annot.log HC16-17.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC05-08.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC05-08.np_annot.log && mv HC05-08.np_annot.log HC05-08.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC05-19.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC05-19.np_annot.log && mv HC05-19.np_annot.log HC05-19.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC14-19.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC14-19.np_annot.log && mv HC14-19.np_annot.log HC14-19.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC05-06.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC05-06.np_annot.log && mv HC05-06.np_annot.log HC05-06.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC19-16.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC19-16.np_annot.log && mv HC19-16.np_annot.log HC19-16.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC05-09.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC05-09.np_annot.log && mv HC05-09.np_annot.log HC05-09.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC12-05.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC12-05.np_annot.log && mv HC12-05.np_annot.log HC12-05.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC17-08.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC17-08.np_annot.log && mv HC17-08.np_annot.log HC17-08.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC09-05.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC09-05.np_annot.log && mv HC09-05.np_annot.log HC09-05.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC12-21.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC12-21.np_annot.log && mv HC12-21.np_annot.log HC12-21.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC12-07.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC12-07.np_annot.log && mv HC12-07.np_annot.log HC12-07.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC08-17.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC08-17.np_annot.log && mv HC08-17.np_annot.log HC08-17.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC08-01.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC08-01.np_annot.log && mv HC08-01.np_annot.log HC08-01.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC20-08.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC20-08.np_annot.log && mv HC20-08.np_annot.log HC20-08.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC20-16.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC20-16.np_annot.log && mv HC20-16.np_annot.log HC20-16.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC10-17.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC10-17.np_annot.log && mv HC10-17.np_annot.log HC10-17.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC10-18.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC10-18.np_annot.log && mv HC10-18.np_annot.log HC10-18.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC15-20.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC15-20.np_annot.log && mv HC15-20.np_annot.log HC15-20.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC06-10.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC06-10.np_annot.log && mv HC06-10.np_annot.log HC06-10.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC10-12.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC10-12.np_annot.log && mv HC10-12.np_annot.log HC10-12.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC18-07.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC18-07.np_annot.log && mv HC18-07.np_annot.log HC18-07.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC09-19.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC09-19.np_annot.log && mv HC09-19.np_annot.log HC09-19.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC18-12.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC18-12.np_annot.log && mv HC18-12.np_annot.log HC18-12.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC05-05.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC05-05.np_annot.log && mv HC05-05.np_annot.log HC05-05.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC20-18.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC20-18.np_annot.log && mv HC20-18.np_annot.log HC20-18.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC14-07.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC14-07.np_annot.log && mv HC14-07.np_annot.log HC14-07.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC15-08.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC15-08.np_annot.log && mv HC15-08.np_annot.log HC15-08.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC05-11.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC05-11.np_annot.log && mv HC05-11.np_annot.log HC05-11.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC10-07.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC10-07.np_annot.log && mv HC10-07.np_annot.log HC10-07.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC08-18.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC08-18.np_annot.log && mv HC08-18.np_annot.log HC08-18.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC06-14.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC06-14.np_annot.log && mv HC06-14.np_annot.log HC06-14.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC10-08.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC10-08.np_annot.log && mv HC10-08.np_annot.log HC10-08.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC15-14.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC15-14.np_annot.log && mv HC15-14.np_annot.log HC15-14.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC09-03.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC09-03.np_annot.log && mv HC09-03.np_annot.log HC09-03.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC12-14.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC12-14.np_annot.log && mv HC12-14.np_annot.log HC12-14.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC03-11.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC03-11.np_annot.log && mv HC03-11.np_annot.log HC03-11.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC03-17.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC03-17.np_annot.log && mv HC03-17.np_annot.log HC03-17.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC01-14.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC01-14.np_annot.log && mv HC01-14.np_annot.log HC01-14.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC13-05.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC13-05.np_annot.log && mv HC13-05.np_annot.log HC13-05.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC18-19.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC18-19.np_annot.log && mv HC18-19.np_annot.log HC18-19.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC21-09.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC21-09.np_annot.log && mv HC21-09.np_annot.log HC21-09.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC01-06.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC01-06.np_annot.log && mv HC01-06.np_annot.log HC01-06.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC15-15.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC15-15.np_annot.log && mv HC15-15.np_annot.log HC15-15.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC01-18.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC01-18.np_annot.log && mv HC01-18.np_annot.log HC01-18.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC03-13.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC03-13.np_annot.log && mv HC03-13.np_annot.log HC03-13.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC05-18.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC05-18.np_annot.log && mv HC05-18.np_annot.log HC05-18.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC04-21.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC04-21.np_annot.log && mv HC04-21.np_annot.log HC04-21.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC15-17.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC15-17.np_annot.log && mv HC15-17.np_annot.log HC15-17.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC12-24.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC12-24.np_annot.log && mv HC12-24.np_annot.log HC12-24.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC19-11.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC19-11.np_annot.log && mv HC19-11.np_annot.log HC19-11.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC12-18.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC12-18.np_annot.log && mv HC12-18.np_annot.log HC12-18.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC13-07.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC13-07.np_annot.log && mv HC13-07.np_annot.log HC13-07.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC13-03.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC13-03.np_annot.log && mv HC13-03.np_annot.log HC13-03.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC01-11.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC01-11.np_annot.log && mv HC01-11.np_annot.log HC01-11.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC16-01.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC16-01.np_annot.log && mv HC16-01.np_annot.log HC16-01.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC21-20.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC21-20.np_annot.log && mv HC21-20.np_annot.log HC21-20.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC04-16.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC04-16.np_annot.log && mv HC04-16.np_annot.log HC04-16.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC18-15.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC18-15.np_annot.log && mv HC18-15.np_annot.log HC18-15.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC09-04.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC09-04.np_annot.log && mv HC09-04.np_annot.log HC09-04.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC05-21.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC05-21.np_annot.log && mv HC05-21.np_annot.log HC05-21.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC10-16.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC10-16.np_annot.log && mv HC10-16.np_annot.log HC10-16.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC01-13.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC01-13.np_annot.log && mv HC01-13.np_annot.log HC01-13.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC20-20.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC20-20.np_annot.log && mv HC20-20.np_annot.log HC20-20.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC03-09.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC03-09.np_annot.log && mv HC03-09.np_annot.log HC03-09.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC09-07.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC09-07.np_annot.log && mv HC09-07.np_annot.log HC09-07.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC10-05.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC10-05.np_annot.log && mv HC10-05.np_annot.log HC10-05.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC04-06.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC04-06.np_annot.log && mv HC04-06.np_annot.log HC04-06.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC14-03.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC14-03.np_annot.log && mv HC14-03.np_annot.log HC14-03.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC20-22.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC20-22.np_annot.log && mv HC20-22.np_annot.log HC20-22.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC21-21.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC21-21.np_annot.log && mv HC21-21.np_annot.log HC21-21.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC15-13.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC15-13.np_annot.log && mv HC15-13.np_annot.log HC15-13.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC20-11.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC20-11.np_annot.log && mv HC20-11.np_annot.log HC20-11.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC01-16.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC01-16.np_annot.log && mv HC01-16.np_annot.log HC01-16.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC12-20.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC12-20.np_annot.log && mv HC12-20.np_annot.log HC12-20.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC08-08.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC08-08.np_annot.log && mv HC08-08.np_annot.log HC08-08.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC01-19.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC01-19.np_annot.log && mv HC01-19.np_annot.log HC01-19.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC18-01.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC18-01.np_annot.log && mv HC18-01.np_annot.log HC18-01.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC03-05.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC03-05.np_annot.log && mv HC03-05.np_annot.log HC03-05.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC09-11.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC09-11.np_annot.log && mv HC09-11.np_annot.log HC09-11.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC15-21.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC15-21.np_annot.log && mv HC15-21.np_annot.log HC15-21.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC04-17.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC04-17.np_annot.log && mv HC04-17.np_annot.log HC04-17.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC17-05.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC17-05.np_annot.log && mv HC17-05.np_annot.log HC17-05.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC03-24.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC03-24.np_annot.log && mv HC03-24.np_annot.log HC03-24.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC05-02.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC05-02.np_annot.log && mv HC05-02.np_annot.log HC05-02.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC01-07.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC01-07.np_annot.log && mv HC01-07.np_annot.log HC01-07.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC04-23.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC04-23.np_annot.log && mv HC04-23.np_annot.log HC04-23.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC15-10.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC15-10.np_annot.log && mv HC15-10.np_annot.log HC15-10.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC14-18.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC14-18.np_annot.log && mv HC14-18.np_annot.log HC14-18.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC18-20.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC18-20.np_annot.log && mv HC18-20.np_annot.log HC18-20.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC21-16.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC21-16.np_annot.log && mv HC21-16.np_annot.log HC21-16.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC01-09.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC01-09.np_annot.log && mv HC01-09.np_annot.log HC01-09.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC05-16.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC05-16.np_annot.log && mv HC05-16.np_annot.log HC05-16.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC01-08.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC01-08.np_annot.log && mv HC01-08.np_annot.log HC01-08.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC12-23.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC12-23.np_annot.log && mv HC12-23.np_annot.log HC12-23.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC15-07.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC15-07.np_annot.log && mv HC15-07.np_annot.log HC15-07.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC18-05.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC18-05.np_annot.log && mv HC18-05.np_annot.log HC18-05.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC03-12.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC03-12.np_annot.log && mv HC03-12.np_annot.log HC03-12.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC20-14.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC20-14.np_annot.log && mv HC20-14.np_annot.log HC20-14.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC12-19.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC12-19.np_annot.log && mv HC12-19.np_annot.log HC12-19.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC09-06.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC09-06.np_annot.log && mv HC09-06.np_annot.log HC09-06.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC04-02.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC04-02.np_annot.log && mv HC04-02.np_annot.log HC04-02.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC17-19.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC17-19.np_annot.log && mv HC17-19.np_annot.log HC17-19.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC09-09.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC09-09.np_annot.log && mv HC09-09.np_annot.log HC09-09.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC09-08.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC09-08.np_annot.log && mv HC09-08.np_annot.log HC09-08.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC14-13.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC14-13.np_annot.log && mv HC14-13.np_annot.log HC14-13.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC17-07.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC17-07.np_annot.log && mv HC17-07.np_annot.log HC17-07.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC06-04.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC06-04.np_annot.log && mv HC06-04.np_annot.log HC06-04.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC14-11.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC14-11.np_annot.log && mv HC14-11.np_annot.log HC14-11.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC17-02.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC17-02.np_annot.log && mv HC17-02.np_annot.log HC17-02.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC13-19.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC13-19.np_annot.log && mv HC13-19.np_annot.log HC13-19.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC13-11.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC13-11.np_annot.log && mv HC13-11.np_annot.log HC13-11.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC16-18.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC16-18.np_annot.log && mv HC16-18.np_annot.log HC16-18.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC17-15.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC17-15.np_annot.log && mv HC17-15.np_annot.log HC17-15.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC03-15.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC03-15.np_annot.log && mv HC03-15.np_annot.log HC03-15.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC18-08.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC18-08.np_annot.log && mv HC18-08.np_annot.log HC18-08.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC04-19.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC04-19.np_annot.log && mv HC04-19.np_annot.log HC04-19.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC21-02.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC21-02.np_annot.log && mv HC21-02.np_annot.log HC21-02.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC10-06.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC10-06.np_annot.log && mv HC10-06.np_annot.log HC10-06.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC12-13.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC12-13.np_annot.log && mv HC12-13.np_annot.log HC12-13.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC05-15.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC05-15.np_annot.log && mv HC05-15.np_annot.log HC05-15.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC19-05.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC19-05.np_annot.log && mv HC19-05.np_annot.log HC19-05.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC21-01.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC21-01.np_annot.log && mv HC21-01.np_annot.log HC21-01.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC14-09.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC14-09.np_annot.log && mv HC14-09.np_annot.log HC14-09.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC01-02.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC01-02.np_annot.log && mv HC01-02.np_annot.log HC01-02.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC10-15.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC10-15.np_annot.log && mv HC10-15.np_annot.log HC10-15.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC17-13.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC17-13.np_annot.log && mv HC17-13.np_annot.log HC17-13.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC06-01.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC06-01.np_annot.log && mv HC06-01.np_annot.log HC06-01.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC15-22.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC15-22.np_annot.log && mv HC15-22.np_annot.log HC15-22.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC03-14.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC03-14.np_annot.log && mv HC03-14.np_annot.log HC03-14.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC21-11.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC21-11.np_annot.log && mv HC21-11.np_annot.log HC21-11.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC09-12.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC09-12.np_annot.log && mv HC09-12.np_annot.log HC09-12.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC05-07.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC05-07.np_annot.log && mv HC05-07.np_annot.log HC05-07.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC20-15.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC20-15.np_annot.log && mv HC20-15.np_annot.log HC20-15.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC08-16.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC08-16.np_annot.log && mv HC08-16.np_annot.log HC08-16.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC12-15.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC12-15.np_annot.log && mv HC12-15.np_annot.log HC12-15.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC06-15.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC06-15.np_annot.log && mv HC06-15.np_annot.log HC06-15.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC03-04.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC03-04.np_annot.log && mv HC03-04.np_annot.log HC03-04.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC03-23.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC03-23.np_annot.log && mv HC03-23.np_annot.log HC03-23.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC05-22.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC05-22.np_annot.log && mv HC05-22.np_annot.log HC05-22.np_annot.success
