sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC02-01.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC02-01.np_annot.log && mv HC02-01.np_annot.log HC02-01.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC02-09.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC02-09.np_annot.log && mv HC02-09.np_annot.log HC02-09.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC02-18.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC02-18.np_annot.log && mv HC02-18.np_annot.log HC02-18.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC02-22.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC02-22.np_annot.log && mv HC02-22.np_annot.log HC02-22.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC02-20.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC02-20.np_annot.log && mv HC02-20.np_annot.log HC02-20.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC02-10.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC02-10.np_annot.log && mv HC02-10.np_annot.log HC02-10.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC02-11.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC02-11.np_annot.log && mv HC02-11.np_annot.log HC02-11.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC02-14.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC02-14.np_annot.log && mv HC02-14.np_annot.log HC02-14.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC02-08.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC02-08.np_annot.log && mv HC02-08.np_annot.log HC02-08.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC02-17.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC02-17.np_annot.log && mv HC02-17.np_annot.log HC02-17.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC02-02.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC02-02.np_annot.log && mv HC02-02.np_annot.log HC02-02.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC02-07.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC02-07.np_annot.log && mv HC02-07.np_annot.log HC02-07.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC02-19.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC02-19.np_annot.log && mv HC02-19.np_annot.log HC02-19.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC02-03.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC02-03.np_annot.log && mv HC02-03.np_annot.log HC02-03.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC02-06.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC02-06.np_annot.log && mv HC02-06.np_annot.log HC02-06.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC02-05.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC02-05.np_annot.log && mv HC02-05.np_annot.log HC02-05.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC02-13.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC02-13.np_annot.log && mv HC02-13.np_annot.log HC02-13.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC02-04.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC02-04.np_annot.log && mv HC02-04.np_annot.log HC02-04.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC02-21.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC02-21.np_annot.log && mv HC02-21.np_annot.log HC02-21.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC02-16.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC02-16.np_annot.log && mv HC02-16.np_annot.log HC02-16.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC02-15.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC02-15.np_annot.log && mv HC02-15.np_annot.log HC02-15.np_annot.success
sh ./SNV_NormalPanel_Serial_Annotation_modified.sh HC02-12.VS_HC_common.cmn_fi.readinfo.readc.rasm2 &> HC02-12.np_annot.log && mv HC02-12.np_annot.log HC02-12.np_annot.success
