circos -conf HC19_sum.conf &> HC19_sum.circos.out
circos -conf HC17_sum.conf &> HC17_sum.circos.out
circos -conf HC15_sum.conf &> HC15_sum.circos.out
circos -conf HC12_sum.conf &> HC12_sum.circos.out
circos -conf HC01_sum.conf &> HC01_sum.circos.out
circos -conf HC10_sum.conf &> HC10_sum.circos.out
circos -conf HC13_sum.conf &> HC13_sum.circos.out
circos -conf HC04_sum.conf &> HC04_sum.circos.out
circos -conf HC20_sum.conf &> HC20_sum.circos.out
circos -conf HC08_sum.conf &> HC08_sum.circos.out
circos -conf HC06_sum.conf &> HC06_sum.circos.out
circos -conf HC14_sum.conf &> HC14_sum.circos.out
circos -conf HC02_sum.conf &> HC02_sum.circos.out
circos -conf HC16_sum.conf &> HC16_sum.circos.out
circos -conf HC03_sum.conf &> HC03_sum.circos.out
circos -conf HC21_sum.conf &> HC21_sum.circos.out
circos -conf HC18_sum.conf &> HC18_sum.circos.out
circos -conf HC09_sum.conf &> HC09_sum.circos.out
circos -conf HC05_sum.conf &> HC05_sum.circos.out
