HC01_merge.s.md.bam
HC01_merge.s.md.bam.bai
HC02_merge.s.md.bam
HC02_merge.s.md.bam.bai
HC03_merge.s.md.bam
HC03_merge.s.md.bam.bai
HC04_blood.s.md.bai
HC04_blood.s.md.bam
HC05_blood.s.md.bai
HC05_blood.s.md.bam
HC06_blood.s.md.bai
HC06_blood.s.md.bam
HC08_blood.s.md.bai
HC08_blood.s.md.bam
HC09_blood.s.md.bai
HC09_blood.s.md.bam
HC10_blood.s.md.bai
HC10_blood.s.md.bam
HC12_blood.s.md.bai
HC12_blood.s.md.bam
HC13_blood.s.md.bai
HC13_blood.s.md.bam
HC14_blood.s.md.bai
HC14_blood.s.md.bam
HC15_blood.s.md.bai
HC15_blood.s.md.bam
HC16_blood.s.md.bai
HC16_blood.s.md.bam
HC17_blood.s.md.bai
HC17_blood.s.md.bam
HC18_blood.s.md.bai
HC18_blood.s.md.bam
HC19_blood.s.md.bai
HC19_blood.s.md.bam
HC20_blood.s.md.bai
HC20_blood.s.md.bam
HC21_blood.s.md.bai
HC21_blood.s.md.bam
